name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: cargo run --release
    - name: Git
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        git config --global user.email "50583248+jy1263@users.noreply.github.com"
        git config --global user.name "Amy Y"
        cd out/output_final && git init && git add -A && git commit -m 'deploy' && git push -f https://github.com/exalt-tools/rotmg-metadata.git master:gh-pages
