name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: "true"
    - name: Cache Testing
      id: cache-testing
      uses: actions/cache@v3
      with:
        path: |
          ./out/*
          !./out/ripped
        key: ${{ runner.os }}-testing
    - name: Cache Test
      run: |
        if [ -e "./out" ]; then
            ls ./out/
        fi

      
    - name: Build
      run: cargo run --release
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        publish_dir: ./out/output_final
